FROM ds.homeawaycorp.com/ha-docker/minipython3:2.2.0
MAINTAINER Anil Pai <apai@homeaway.com>

ENV APP_NAME ae-audatar
ENV APP_HOME /usr/local/homeaway/${APP_NAME}
ENV APP_LOGS ${APP_HOME}/logs

EXPOSE 8080

COPY audatar ${APP_HOME}/audatar
COPY audatar-ui ${APP_HOME}/audatar-ui
COPY docs/jars /opt/jars
COPY setup_scripts ${APP_HOME}/setup_scripts
COPY manage.py ${APP_HOME}/manage.py
COPY favicon.ico ${APP_NAME}/favicon.ico
COPY tests ${APP_HOME}/tests
COPY tox.ini ${APP_HOME}/tox.ini
COPY requirements.txt ${APP_HOME}/requirements.txt
COPY test-requirements.txt ${APP_HOME}/test-requirements.txt
COPY write_secrets_file.py ${APP_HOME}/write_secrets_file.py


RUN echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
    apt-get update && apt-get install -y software-properties-common && \
    add-apt-repository -y ppa:webupd8team/java && apt-get update && \
    apt-get install -y oracle-java8-installer && \
    apt-get install oracle-java8-set-default


RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive && apt-get install -y tzdata && \
    apt-get install -y python3 python3-dev python3-pip g++ ant git-all \
    libboost-dev libboost-test-dev libboost-program-options-dev \
    libevent-dev automake libtool flex bison pkg-config g++ \
    libpq-dev libssl-dev libxml2-dev libxslt1-dev \
    libldap2-dev libsasl2-dev && \
    python3 -m pip install --upgrade pip==18.1 && \
    pip3 install cython && \
    pip3 install -r ${APP_HOME}/requirements.txt && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV JAVA_HOME /usr/lib/jvm/java-8-oracle
RUN mkdir -p ${APP_LOGS} && sync
VOLUME ${APP_LOGS}
WORKDIR ${APP_HOME}
